#!/bin/bash

echo "test 1: cluster readiness 1"
docker-compose up -d test_executor server1
#sleep 5s && docker-compose up -d server2 server3 &
docker-compose exec test_executor /utils/wait_for_cluster
sleep 10s
docker-compose down
