openapi: "3.0.0"

info:
  title: LogDB Server
  version: "1.0"

servers:
    - url: /api/v1/

components:
  parameters:
    LogId:
      name: log_id
      in: path
      description: Log identifier.
      example: v9UuI2
      required: true
      schema:
        type: string
    Filters:
      name: filters
      in: query
      description: List of base64-encoded regex filters to be matched against log lines.
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: false

paths:
  /log/{log_id}/query:
    get:
      summary: Query a log.
      operationId: server.query
      parameters:
        - $ref: "#/components/parameters/LogId"
        - $ref: '#/components/parameters/Filters'
      responses:
        200:
          description: Query a log...
          content:
            application/json:
              schema:
                type: object
